send-welcome-message: true
welcome-message:
  - ""
  - "&f&m             &b Welcome &a{player} &f&m             "
  - ""
  - "&dServerName Network &eenjoy and have fun"
  - "&eyou need to test all game modes!"
  - ""
  - "&f&m                                                       "


#You can use sounds from https://www.digminecraft.com/lists/sound_list_pc.php
send-welcome-sound: true
welcome-sound: ENTITY_PLAYER_LEVELUP

#If you have PlaceholderAPI on your plugin folder. You can use any placeholder.
scoreboard:
  enabled: true
  title: '&5&lServerName Network'
  lines:
    - blank
    - '&d| &f&lNick » &d%playername%'
    - blank
    - '&d| &f&lMiniLobby » &d#2'
    - blank
    - www.server.net

no-break: true
no-drop: true
no-pickup: true
no-damage: true
no-pvp: true
no-inventoryclick: true
never-rain: true
#If you want you can also just use /gamerule doDaylightCycle false
always-day: true


spawn:
  enabled: true
  always-teleport: true
  hide-players: true
  default-game-mode: adventure
  location-set-message: "&aSpawn location has been set."
  no-spawn-set-message: "&cSpawn location has not yet been set."
  spawn-disabled-message: "&cSpawn functionality is currently disabled.."
  world-not-exist-message: "&cThe world specified in the spawn location does not exist.."
  only-players-message: "&cOnly players can execute this command."
  no-permission-message: "&cYou do not have permission to execute this command."
  location-deleted-message: "&aSpawn location deleted."
  already-set-message: "&cA spawn location already exists. Use /spawn del to remove it first."
  teleported-message: "&aYou have been teleported to the spawn location."

#You can use [player] to make a player execute the command. [msg] to send a message to the player and [console] to make a console execute command (Has not been tested [console]. Be careful)
items-join-enabled: true
items:
  server-selector:
    id: COMPASS
    slot: 0
    displayname: '&bServer selector'
    amount: 1
    lore:
      - '&7Mira la información'
      - '&7de nuestros servidores'
    permission-node: '' # Empty means that is not permission required to give the item
    command: '[player] servers'
  discord:
    id: PAPER
    slot: 8
    displayname: '&5Join to our Discord'
    amount: 1
    lore:
      - '&7Join to our discord'
      - '&7server'
    permission-node: '' # Empty means that is not permission required to give the item
    command: '[msg] &5Discord: https://discord.gg/server'
  buycraft:
    id: GOLD_INGOT
    slot: 4
    displayname: '&aShop'
    amount: 1
    lore:
      - '&7Look our'
      - '&7store'
    permission-node: '' # Empty means that is not permission required to give the item
    command: '[msg] &aTienda: &fserver.tebex.io'