name: CustomMiniLobby
version: '${project.version}'
main: org.dark.customminilobby.CustomMiniLobby
api-version: '1.21'
softdepend: [PlaceholderAPI]
commands:
  cml:
    description: "Comandos para manejar el lobby."
    usage: "/cml [set|del|reload]"
    permission: "cml.spawn"
    permission-message: "No tienes permiso para usar este comando."
  mostrarcara:
    description: "Muestra la cara de la skin de un jugador en un mapa."
    usage: "/mostrarcara <nombre_jugador>"
    permission: "cml.imagemap"